### ISSUE TITLE
Error generating builder for any data class

### ISSUE THREAD

**Issue by OsaSoft** [MaibornWolff/intellij-kotlin-builder-plugin#1]
Trying to generate a builder for any, even the simplest, data class does not work. See attached screenshot.

IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: search.everywhere.settings=true, actionSystem.force.alt.gr=true
Non-Bundled Plugins: by.vkatz.decorate_mode_switcher (2.2.1), com.intellij.apacheConfig (211.6693.108), com.jetbrains.plugins.ini4idea (211.6693.44), com.karateca.jstoolbox (1.10), manjaro.mpb (1.6), org.intellij.plugins.hcl (0.7.10), GenerateSerialVersionUID (3.0.3), VisualVMLauncher (1.20.203.4204.0), de.u-mass.idea.copyConstructor (1.2), org.apache.camel (0.7.8), org.jetbrains.jumpToLine (0.1.6), Spock Framework Enhancements (0.12), com.kukido.eclipser (0.8.8), org.jetbrains.kotlin (211-1.5.21-release-317-IJ7442.40), kotest-plugin-intellij (1.1.36-IC-2021.1), Osmorc (211.6693.65), org.intellij.scala (2021.1.21), com.jetbrains.php (211.7628.25), Pythonid (211.7628.24), de.maibornwolff.its.intellij-kotlin-builder (1.1.0)
Kotlin: 211-1.5.21-release-317-IJ7442.40

![image](https://user-images.githubusercontent.com/8895463/125962427-2371852f-17d7-485b-a617-3447f0fea1d8.png)

**Comment by olexs** [comment]
The screenshot looks like your cursor is on the second line (```val language: Language```). At this time the builder only works if the cursor is directly on the class name. Could you try that?

**Comment by OsaSoft** [comment]
this time got this:
```
java.lang.NoSuchMethodError: 'org.jetbrains.kotlin.analyzer.AnalysisResult org.jetbrains.kotlin.idea.resolve.ResolutionFacade.analyzeWithAllCompilerChecks(java.util.Collection)'
	at de.maibornwolff.its.buildergenerator.generator.BuilderGenerator.generateBuilderForDataClass(BuilderGenerator.kt:87)
	at de.maibornwolff.its.buildergenerator.actions.GenerateBuilderAction.generateBuilder(GenerateBuilderAction.kt:39)
	at de.maibornwolff.its.buildergenerator.actions.GenerateBuilderAction.actionPerformed(GenerateBuilderAction.kt:30)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:267)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:241)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:231)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:217)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1511)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:173)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:36)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1507)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:163)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:343)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:290)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:138)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:168)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:153)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:141)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:266)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:460)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:432)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:373)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:275)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:354)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:112)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:148)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:102)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:809)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	```

**Comment by olexs** [comment]
Interesting, that looks like a dependency issue... I'll look into what's going on there, thanks for a detailed report!

**Comment by OsaSoft** [comment]
youre very welcome! Id love for this to work 😅 Ive had to create builders in java and then convert them to kotlin, which is a bit tedious
